version: '3.9'

volumes:
  cache:
    driver: local

services:
  app:
    build:
      context: .
    container_name: taskList
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taskList?currentSchema=taskList
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - '8080:8080'

  db:
    image: ubuntu/postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskList
    ports:
      - '5433:5432'
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass amdzYWtqamxscEtLUEtGS3NNTk1aTktERg==
    volumes:
      - cache:/data