spring:
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      password:
  datasource:
    #!!! yaml работает корректно только со схемой, название которой состоит из маленьких букв!!!
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=tasklist
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=tasklist
#    url: jdbc:postgresql://localhost:5433/taskList?currentSchema=taskList  #OK для обращения в Docker извне
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    jpa:
      database: postgresql
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          ddl-auto: none

  sql:
    init:
      mode: never # чтобы работал liquibase
      continue-on_error: false
#      data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: false
    default-schema: tasklist
security:
  jwt:
    secret: Z3NqZ2hnamdoZXdqYmpmNzJ5MjhodWZqZTJudWVmdWFqZm5mbmVqZm5h
    access: 360000
    refresh: 259200000
springdoc:
  override-with-generic-response: false